# Setup options for UI-3160-C-HQ Rev 2.1

# Auto-exposure
set_autoExp: true

# Area of interest [original resolution is 1920*1200]
set_aoi: true
aoi_x: 640 # (1920-640)/2
aoi_y: 560 # 1200-640
aoi_w: 640
aoi_h: 640

# Sensor gain [1x-4x]
set_gain: true
gain: 50 # 50% = 2x

# Frame rate (smaller AOI allows higher fps values)
set_fps: false
fps: 25.0