# Cones geometry, in meters (from FS rules)
smallConeHeight: 0.35 #0.325
largeConeHeight: 0.35 #0.505

# Camera position, in meters
cameraHeight: 1.5

# Maximum accepted distance to consider cone, in meters
maxDistance: 15