# Configuration file for YOLO inference

# Fixed options: image_size = 640, batch_size = 1

# Inference options
model_path: /path/to/engine
model_type: YOLOv5                                           # [YOLOv5, YOLOv8, YOLOv10, YOLOv11]
conf_thres: 0.5                                              # [0.001 - 1]
iou_thres: 0.7                                               # [0.001 - 1]
max_det: 300                                                  
normalize: false                                             # flag to enable Z-Score Normalization with mean and std values
mean: [0.406, 0.456, 0.485]                                  # (B,G,R) IMAGENET (use scripts/get_zscore_values.py for custom values)
stddev: [0.225, 0.224, 0.229]                                # (B,G,R) IMAGENET

# Classes (FSOCO dataset)
nc: 5
classes: # just for clarity, changing mapping does not make any effect                                                   
  0: yellow
  1: blue
  2: orange
  3: large_orange
  4: unknown